### ISSUE TITLE
Uniform naming convention of maps from cpm/rcm/gcm data

### ISSUE THREAD

**Issue by geek-yang** [eucp-project/data-catalogue#41]
We need the same naming rules for the maps used in `past performance`  `future change`  `Analyse` tabs in cpm page. This also influences the options in the dropdown menu in each `.vue` file for the related tabs, and therefore corresponds to issue #37 .

It is recommended to address this issue together with issue #37.

**Comment by Peter9192** [comment]
Thanks for opening. Do you want to go ahead and suggest a naming convention?

**Comment by geek-yang** [comment]
> Thanks for opening. Do you want to go ahead and suggest a naming convention?

Thanks @Peter9192, you are super fast 😅 (I was busy dropping some comments for the related PR #40 ). Yep, I will think about it. We need to find a way to make those names consistent with the deliverable 3.3, and close to the file names of the data provided by Petter Lind and Tom (easy match, clean code).

**Comment by geek-yang** [comment]
The map title should be `{group} {project} | {season} | {region}` (e.g. CMCC CPM | DJF | AL) and the output file names should look like `{group}_{project}_{season}.png` (e.g. cmcc_cpm_djf_al.png).
