### ISSUE TITLE
Hiding "impossible" models when navigating between regions

### ISSUE THREAD

**Issue by bvreede** [eucp-project/data-catalogue#56]
Following the discussion in #51, it would be good to implement this. At the moment, a user can find "impossible" results by selecting a combination of model/season/etc, then moving to another region that this model does/should not show. When starting at this region, the model does not appear in the dropdown. However, when moving towards that region with the selection already made, the results show anyway. Sometimes the CPM image is missing. Sometimes it is not. In either of those situations, there should be a clear result showing that this model does not work for the selected region.

**Comment by geek-yang** [comment]
Thanks for the suggestion. Will improve this by using the ["watcher"](https://vuejs.org/guide/essentials/watchers.html) feature of vue/nuxt.
